name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
      continue-on-error: true

    - name: Type check
      run: npx tsc --noEmit
      continue-on-error: true

    - name: Report Status
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo, number } = context.issue;
          const lintResult = '${{ steps.lint.outcome }}';
          const typeCheckResult = '${{ steps.type-check.outcome }}';
          
          let body = '## PR Validation Results\n\n';
          body += `- Lint: ${lintResult === 'success' ? '✅' : '❌'}\n`;
          body += `- Type Check: ${typeCheckResult === 'success' ? '✅' : '❌'}\n`;
          
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body
          }); 